package wedding_venue_admin;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.Timer;

import java.awt.Color;
import java.awt.Font;
import javax.swing.border.LineBorder;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.SwingConstants;
import javax.swing.JSeparator;
import java.awt.SystemColor;


public class booking extends javax.swing.JFrame {
	private String[] images ={"1.jpg","2.jpg","3.png","4.jpg","5.jpg","6.jpg"};
    /**
     * Creates new form booking
     */
    public booking() {
    	getContentPane().setBackground(SystemColor.textHighlight);
    	setTitle("EVENT PLANNING");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Prateek\\Desktop\\project\\iconimage.jpg"));
        initComponents();
      L1.setVisible(false);

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        L1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jButton7 = new javax.swing.JButton();
        jButton7.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton7.setFocusPainted(false);
        jButton7.setForeground(new Color(255, 255, 255));
        jButton8 = new javax.swing.JButton();
        jButton8.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton8.setFocusPainted(false);
        jButton8.setForeground(new Color(255, 255, 255));
        jButton9 = new javax.swing.JButton();
        jButton9.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton9.setFocusPainted(false);
        jButton9.setForeground(new Color(255, 255, 255));
        jButton11 = new javax.swing.JButton();
        jButton11.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton11.setFocusPainted(false);
        jButton11.setForeground(new Color(255, 255, 255));

        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 770));
        setSize(new java.awt.Dimension(1000, 770));
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PNR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(366, 530, 116, 35);
        getContentPane().add(j1);
        j1.setBounds(492, 530, 200, 35);

        jButton1.setBackground(new java.awt.Color(255, 192, 203));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("STATUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(413, 590, 166, 35);

        L1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L1.setForeground(new Color(0, 0, 0));
        L1.setText("BOOKING IS CONFIRMED");
        getContentPane().add(L1);
        L1.setBounds(271, 636, 449, 44);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Booking Status\r\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(238, 396, 540, 60);

        jButton7.setBackground(new Color(0, 0, 153));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Feedback");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(399, 330, 200, 35);

        jButton8.setBackground(new Color(0, 0, 153));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(798, 330, 201, 35);

        jButton9.setBackground(new Color(0, 0, 153));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("View Event");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(598, 330, 200, 35);

        jButton11.setBackground(new Color(0, 0, 153));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton11.setText("Book An Event");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1, 330, 200, 35);
        
        label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\icon.png"));
        label.setOpaque(true);
        label.setBackground(new Color(0, 0, 0));
        label.setBorder(new LineBorder(new Color(0, 0, 0), 5, true));
        label.setBounds(1, 1, 991, 320);
        Timer timer= new Timer(1000, new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				int n= (int) Math.floor( Math.random() * 6);
				String image=images[n];
				label.setIcon(new ImageIcon("src\\images\\"+ image));
			}
			
		});
		timer.start();

        getContentPane().add(label);
        
        btnBookingStatus = new JButton();
        btnBookingStatus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		booking.main(null);
        		dispose();
        	}
        });
        btnBookingStatus.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        btnBookingStatus.setFocusPainted(false);
        btnBookingStatus.setForeground(new Color(255, 255, 255));
        btnBookingStatus.setText("Booking Status");
        btnBookingStatus.setFont(new Font("Times New Roman", Font.BOLD, 18));
        btnBookingStatus.setBackground(new Color(0, 0, 153));
        btnBookingStatus.setBounds(200, 330, 200, 35);
        getContentPane().add(btnBookingStatus);
        
        separator = new JSeparator();
        separator.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        separator.setForeground(new Color(0, 0, 0));
        separator.setBackground(new Color(0, 0, 0));
        separator.setBounds(387, 470, 248, 2);
        getContentPane().add(separator);
        
        label_1 = new JLabel("");
        label_1.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\Webp.net-resizeimage (3).jpg"));
        label_1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        label_1.setBounds(28, 391, 942, 327);
        getContentPane().add(label_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       try{
           int a=Integer.parseInt(j1.getText()); 
           Connect cn=new Connect();
			Connection con=cn.conn();
            System.out.println("a"); 
           
            PreparedStatement pst=con.prepareStatement("select * from REGISTRATION where pnr=?");
            pst.setInt(1,a);
             ResultSet rs=pst.executeQuery();
           if(rs.next()){  
             System.out.println("successfully transmitted");
             L1.setVisible(true);
   
       }
           else{
              // L2.setVisible(true);
              JOptionPane.showMessageDialog(null,"wrong!! contact to our developers");
               System.exit(0);
               /// SORRY LINK DEDE CONTACT VALE PAGE KA 
               
               //contact c =new contact(); 
               //c.setVisible(true); 
               
           }
       }
      
        
       catch(Exception e){
           System.out.println(e); 
       } 
  

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Feedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Home.main(null);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    	venue.main(null);
    	dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    	book_venue.main(null);
    	dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JTextField j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private JLabel label;
    private JButton btnBookingStatus;
    private JLabel label_1;
    private JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
