package wedding_venue_admin;

import static java.lang.Double.sum;
import static java.lang.Integer.sum;
import static java.lang.Long.sum;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.Timer;

import java.awt.Color;
import javax.swing.border.LineBorder;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import java.awt.SystemColor;
import javax.swing.JButton;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class book_venue extends javax.swing.JFrame {
	 private String[] images ={"1.jpg","2.jpg","3.png","4.jpg","5.jpg","6.jpg"};
    /**
     * Creates new form book_venue
     */
    public book_venue() {
    	getContentPane().setBackground(SystemColor.textHighlight);
    	setTitle("EVENT PLANNING");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Prateek\\Desktop\\project\\iconimage.jpg"));
        initComponents();
    }
    public book_venue(String para){
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        j6 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        c9 = new javax.swing.JComboBox<>();
        c10 = new javax.swing.JComboBox<>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        f3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton6.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        c11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        c12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton5.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton7 = new javax.swing.JButton();
        jButton7.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton7.setFocusPainted(false);
        jButton7.setForeground(new Color(255, 255, 255));
        jButton8 = new javax.swing.JButton();
        jButton8.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton8.setFocusPainted(false);
        jButton8.setForeground(new Color(255, 255, 255));
        jButton9 = new javax.swing.JButton();
        jButton9.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton9.setFocusPainted(false);
        jButton9.setForeground(new Color(255, 255, 255));
        jButton11 = new javax.swing.JButton();
        jButton11.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton11.setFocusPainted(false);
        jButton11.setForeground(new Color(255, 255, 255));
        jLabel28 = new javax.swing.JLabel();
        jLabel28.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel28.setHorizontalAlignment(SwingConstants.CENTER);

        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 770));
        setSize(new java.awt.Dimension(1000, 770));
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator4.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jSeparator4.setForeground(new Color(0, 0, 0));
        
                jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
                jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
                jSeparator4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                getContentPane().add(jSeparator4);
                jSeparator4.setBounds(490, 455, 2, 230);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setText("Name");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(47, 455, 90, 29);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("PNR");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(47, 535, 82, 29);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setText("Event Type");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(47, 575, 128, 29);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("Event Place");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(47, 626, 139, 29);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("Date");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(560, 455, 102, 29);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel23.setText("Seating");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(560, 545, 114, 29);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setText("Flowers");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(560, 500, 120, 29);
        getContentPane().add(j6);
        j6.setBounds(198, 455, 226, 29);
        getContentPane().add(j5);
        j5.setBounds(198, 535, 226, 29);

        c9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        c9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "MARRIAGE", "BIRTHDAY PARTY", "BREAKUP PARTY" }));
        getContentPane().add(c9);
        c9.setBounds(198, 575, 226, 29);

        c10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        c10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "TAJ HOTEL", "OBEROI HOTEL" }));
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });
        c10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c2KeyReleased(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(198, 626, 226, 32);
        getContentPane().add(jDateChooser3);
        jDateChooser3.setBounds(710, 455, 226, 29);
        getContentPane().add(f3);
        f3.setBounds(710, 500, 226, 29);

        jButton6.setBackground(new Color(0, 128, 128));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("SEARCH PNR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(261, 495, 162, 29);
        getContentPane().add(c11);
        c11.setBounds(710, 545, 226, 29);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setText("Total Cost");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(560, 588, 139, 29);
        getContentPane().add(c12);
        c12.setBounds(710, 588, 95, 29);

        jButton5.setBackground(new Color(0, 128, 128));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Calculate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(827, 588, 109, 29);

        jButton7.setBackground(new Color(0, 0, 153));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Feedback");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(390, 330, 195, 35);

        jButton8.setBackground(new Color(0, 0, 153));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(787, 330, 205, 35);

        jButton9.setBackground(new Color(0, 0, 153));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("View Venue");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(585, 330, 202, 35);

        jButton11.setBackground(new Color(0, 0, 153));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton11.setText("Book An  Event");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1, 330, 195, 35);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel28.setText("Book An Event");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(390, 374, 241, 60);
        
        final JLabel label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\icon.png"));
        label.setBorder(new LineBorder(new Color(0, 0, 0), 5, true));
        label.setOpaque(true);
        label.setBackground(new Color(0, 0, 0));
        label.setBounds(1, 1, 992, 320);
        getContentPane().add(label);
        
        JButton btnBookingStatus = new JButton();
        btnBookingStatus.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		booking.main(null);
        		dispose();
        	}
        });
        btnBookingStatus.setText("Booking Status");
        btnBookingStatus.setForeground(Color.WHITE);
        btnBookingStatus.setFont(new Font("Times New Roman", Font.BOLD, 18));
        btnBookingStatus.setFocusPainted(false);
        btnBookingStatus.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        btnBookingStatus.setBackground(new Color(0, 0, 153));
        btnBookingStatus.setBounds(195, 330, 195, 35);
        getContentPane().add(btnBookingStatus);
        
        JButton btnSubmit = new JButton("Submit");
        btnSubmit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		try{
					Connect cn=new Connect();
				    Connection con=cn.conn();
				    String etype=c9.getSelectedItem().toString();
				    String eplace=c10.getSelectedItem().toString();
				    String bname=j6.getText();
				    String flower=f3.getText();
				    int pnr1=Integer.parseInt(j5.getText());
				    int seating=Integer.parseInt(c11.getText());
				    int tcost =Integer.parseInt(c12.getText());
				    PreparedStatement ps=con.prepareStatement("insert into book_venue values(?,?,?,?,?,?,?)");
					ps.setString(1,bname);
					ps.setInt(2,pnr1);
					ps.setString(3,etype);
					ps.setString(4,eplace);
					ps.setString(5,flower);
					ps.setInt(6,seating);
					ps.setInt(7,tcost);
					int i=ps.executeUpdate();
					if(i==1)
					{
						JOptionPane.showMessageDialog(null, "ADDED Venue Successfully !!");
					}
				}catch(Exception e){
					   JOptionPane.showMessageDialog(null, " Unsuccessful Operation !!");
					e.printStackTrace();
				}
			}
        		
        	
        });
        btnSubmit.setBackground(new Color(0, 128, 128));
        btnSubmit.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        btnSubmit.setFont(new Font("Times New Roman", Font.BOLD, 18));
        btnSubmit.setBounds(797, 657, 139, 29);
        getContentPane().add(btnSubmit);
        
        label_1 = new JLabel("");
        label_1.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\Webp.net-resizeimage (3).jpg"));
        label_1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        label_1.setBounds(23, 384, 943, 335);
        getContentPane().add(label_1);
        Timer timer= new Timer(1000, new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				int n= (int) Math.floor( Math.random() * 6);
				String image=images[n];
				label.setIcon(new ImageIcon("src\\images\\"+ image));
			}
			
		});
		timer.start();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String a=j6.getText();
            Connect cn=new Connect();
			Connection con=cn.conn();
			
            PreparedStatement pst=con.prepareStatement("select * from REGISTRATION	 where name=?");
            pst.setString(1,a) ;
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString(6);
                j5.setText(""+add1);
                JOptionPane.showMessageDialog(this," "+ add1);
            }

            else{
                JOptionPane.showMessageDialog(null,"oops !! database not found");
            }
        }

        catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void c2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c2KeyReleased

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        if(!((c2.getSelectedItem().toString().equals("SELECT")) &&( c1.getSelectedItem().toString().equals("SELECT")))){

            c3.setText("500");
        }

    }//GEN-LAST:event_c2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a =Integer.parseInt(s1.getText()) ;
        int sumall;
        //int g =Integer.parseInt(g1.getText()) ;

        int f =Integer.parseInt(f1.getText()) ;
        String e = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getName();
        if(a>1&&a<=100&&f>1){
            int sum=1600 ;

        }
        else if (a>=100&&a<=500&&f>10){
            int sum2=50000;
        }

        sumall=1600+50000+500;
        c4.setText("52k");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Feedback.main(null);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Home.main(null);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    	venue.main(null);
    	dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    	book_venue.main(null);
    	dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_venue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c6;
    private javax.swing.JTextField c7;
    private javax.swing.JTextField c8;
    private javax.swing.JComboBox<String> c9;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private JLabel label_1;
}
