package wedding_venue_admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.awt.Toolkit;
import javax.swing.border.LineBorder;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.JSeparator;
import java.awt.SystemColor;


public class Sign_Up extends javax.swing.JFrame {
	private String[] images ={"1.jpg","2.jpg","3.png","4.jpg","5.jpg","6.jpg"};
    /**
     * Creates new form SignUp
     */
    public Sign_Up() {
    	getContentPane().setBackground(SystemColor.textHighlight);
    	setTitle("EVENT PLANNING");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Prateek\\Desktop\\project\\iconimage.jpg"));
        initComponents();
       
         setSize(1000,770);
        setLocationRelativeTo(null);
    }
 
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        b1 = new javax.swing.JButton();
        b1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton2 = new javax.swing.JButton();
        jButton2.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        tf6 = new javax.swing.JPasswordField();
        tf7 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jButton5.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton5.setFocusPainted(false);
        jButton5.setForeground(new Color(255, 255, 255));
        jButton6 = new javax.swing.JButton();
        jButton6.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton6.setFocusPainted(false);
        jButton6.setForeground(new Color(255, 255, 255));
        jButton7 = new javax.swing.JButton();
        jButton7.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton7.setFocusPainted(false);
        jButton7.setForeground(new Color(255, 255, 255));
        jButton8 = new javax.swing.JButton();
        jButton8.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton8.setFocusPainted(false);
        jButton8.setForeground(new Color(255, 255, 255));
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 770));
        setSize(new java.awt.Dimension(1000, 770));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 482, 66, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(63, 530, 84, 29);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 355, 0, 0);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Email Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(514, 482, 160, 29);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(514, 530, 160, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(63, 600, 104, 29);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(514, 578, 160, 29);

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf2KeyPressed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(173, 482, 200, 29);

        tf3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf3KeyPressed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(173, 530, 200, 50);

        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf4KeyPressed(evt);
            }
        });
        getContentPane().add(tf4);
        tf4.setBounds(173, 600, 200, 29);

        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf5KeyPressed(evt);
            }
        });
        getContentPane().add(tf5);
        tf5.setBounds(686, 482, 200, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("CUSTOMER REGISTRATION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(182, 384, 643, 54);

        b1.setBackground(new Color(0, 128, 128));
        b1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b1.setText("SUBMIT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(592, 651, 127, 29);

        jButton2.setBackground(new Color(0, 128, 128));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(759, 651, 127, 29);

        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf6KeyPressed(evt);
            }
        });
        getContentPane().add(tf6);
        tf6.setBounds(684, 530, 200, 29);

        tf7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf7KeyPressed(evt);
            }
        });
        getContentPane().add(tf7);
        tf7.setBounds(684, 578, 200, 29);

        jButton5.setBackground(new Color(0, 0, 153));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1, 330, 250, 35);

        jButton6.setBackground(new Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("Contact Us");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 330, 250, 35);

        jButton7.setBackground(new Color(0, 0, 153));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("About Us");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(500, 330, 250, 35);

        jButton8.setBackground(new Color(0, 0, 153));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(750, 330, 242, 35);
        
        label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\icon.png"));
        label.setBorder(new LineBorder(new Color(0, 0, 0), 5, true));
        label.setBounds(1, 1, 991, 320);
        Timer timer= new Timer(1000, new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				int n= (int) Math.floor( Math.random() * 6);
				String image=images[n];
				label.setIcon(new ImageIcon("src\\images\\"+ image));
			}
			
		});
		timer.start();
        getContentPane().add(label);
        
        separator = new JSeparator();
        separator.setOrientation(SwingConstants.VERTICAL);
        separator.setForeground(new Color(0, 0, 0));
        separator.setBackground(new Color(0, 0, 0));
        separator.setBounds(443, 467, 2, 170);
        getContentPane().add(separator);
        
        label_1 = new JLabel("");
        label_1.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\Webp.net-resizeimage (3).jpg"));
        label_1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        label_1.setBounds(21, 382, 937, 330);
        getContentPane().add(label_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed

              // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

     
        String name;
        String address;
        String mobile_no;
        String email_id;
        String password;
        String confirm_password;
        
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
      String b=tf2.getText();
         String A=tf3.getText();
          String MN=tf4.getText();
           String EI =tf5.getText();
            String P=tf6.getText();
             String CP=tf7.getText();
       
            if (b.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is required", "Error", JOptionPane.ERROR_MESSAGE);
          
            return;
            }
              if (A.equals("")) {
            JOptionPane.showMessageDialog(null, "Address is required", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
             }
               if (MN.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile Number is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
             }
              if (EI.equals("")) {
            JOptionPane.showMessageDialog(null, "Email Id is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
             }
               if (P.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
             }
                if (CP.equals("")) {
            JOptionPane.showMessageDialog(null, "Confirm Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
             }
                 
                    name=b;
                    address=A;
                    email_id=EI;
                    password=P;
                    confirm_password=CP;
                   
                  try
                  {
                      BigInteger mn =  new BigInteger(MN);
                    mobile_no = MN;
                  }catch(Exception e)
                  {
                      JOptionPane.showMessageDialog(null,"enter only number","error",JOptionPane.ERROR_MESSAGE);
                     return; 
                  }
                
                    if(EI.contains("@"))
                    {
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"no @  is present in Email Id ","error",JOptionPane.ERROR_MESSAGE);
                        
                        return;
                    }
                    
                    if(P.contains("@"))
                    {
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Atleast 1 @ is required in Password","error",JOptionPane.ERROR_MESSAGE);
                       return; 
                    }
                   
                   
                    
                   
                    if(CP.matches(P))
                    {
                        
                    }
                        else
                    {
                        JOptionPane.showMessageDialog(null,"Password does not match","error",JOptionPane.ERROR_MESSAGE);
                    return;
                    }
                  
              
                
        try{
        	Connect cn=new Connect();
			Connection con=cn.conn();
            String ab =tf2.getText(); 
            String Ab=tf3.getText();
          int  MNb=Integer.parseInt(tf4.getText());
           String EIb=tf5.getText();
            String Pb=tf6.getText();
          
           PreparedStatement pst=con.prepareStatement (" insert into REGISTRATION(name ,address,mob_no,email_id,password) values(?,?,?,?,?)");
           pst.setString(1,ab) ;
           pst.setString(2,Ab) ;
            pst.setInt(3,MNb) ;
            pst.setString(4,EIb);
            pst.setString(5,Pb);
           // pst.setInt(6,u) ; 
           // pst.setString(7,i);
          int x=pst.executeUpdate();
          if(x==1){
            JOptionPane.showMessageDialog(null, "sign up successfully !! now you login");
          }
       }
       catch(Exception e){
           System.out.println(e); 
       }
        ////RANDOM CLASS GENEREATED FOR THE GENEARATION OF THE PNR NO
        try
{
        	Connect cn=new Connect();
			Connection con=cn.conn();
            Random random = new Random();
            int number=0;
      
        for(int counter=1001; counter<=1001;counter++){
        number = 1+random.nextInt(100000);
       
       JOptionPane.showMessageDialog(null,"the pnr no is "+number) ;
         JOptionPane.showMessageDialog(null,"one pnr number at a time  "+number) ;
         
          
         
         break ;
        }
        ////////////////////////////////////////////////////
       String a=tf2.getText();
      
            PreparedStatement pst=con.prepareStatement("select * from REGISTRATION where name=?");
            pst.setString(1,a);
             ResultSet rs=pst.executeQuery();
             System.out.println("successfully transmitted");
        ///second prepared statement starts from here
            
           
         PreparedStatement pt=con.prepareStatement ("UPDATE REGISTRATION SET pnr = ? where name=?");
           pt.setInt(1,number) ;
            pt.setString(2,a) ;
          int x=pt.executeUpdate();
          System.out.println("test"+x);
            JOptionPane.showMessageDialog(null,"all done");  
      
}
        
      //  String a=tf2.getText();
        
                 catch(Exception e){
      //                  JOptionPane.showMessageDialog(null,"all done");  
                         }
        
       
       
       
       
       
       
       
       
       
   //    new book_venue(number).setVisible(true); 
       
       
       

     Login_Sys.main(null);
     dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    Home.main(null);
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home.main(null);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       Contact_Us.main(null);
       dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        About_Us.main(null);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       Login_Sys.main(null);
       dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tf2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         tf3.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf2KeyPressed

    private void tf4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         tf5.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf4KeyPressed

    private void tf3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         tf4.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf3KeyPressed

    private void tf5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         tf6.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf5KeyPressed

    private void tf6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         tf7.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf6KeyPressed

    private void tf7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf7KeyPressed
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         b1.requestFocus();
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tf7KeyPressed

   
    /**
     * 
     * @param args the command line arguments
     */
   
  public void actionPrformed(ActionEvent e) throws SQLException
  {
    
  }
    public static void main(String args[]) {

    
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JPasswordField tf6;
    private javax.swing.JPasswordField tf7;
    private JLabel label;
    private JLabel label_1;
    private JSeparator separator;
}
