package wedding_venue_admin;
import javax.swing.JFrame;
import javax.swing.Timer;

import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class venue extends javax.swing.JFrame {
	 private String[] images ={"1.jpg","2.jpg","3.png","4.jpg","5.jpg","6.jpg"};
    /**
     * Creates new form venue
     */
    public venue() {
    	getContentPane().setBackground(SystemColor.textHighlight);
    	setTitle("EVENT PLANNING");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Prateek\\Desktop\\project\\iconimage.jpg"));
        initComponents();
        setSize(1000,770);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jLabel3 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton3.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton3.setFocusPainted(false);
        jButton3.setForeground(new Color(255, 255, 255));
        jButton4 = new javax.swing.JButton();
        jButton4.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton4.setFocusPainted(false);
        jButton4.setForeground(new Color(255, 255, 255));
        jButton6 = new javax.swing.JButton();
        jButton6.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton6.setFocusPainted(false);
        jButton6.setForeground(new Color(255, 255, 255));
        jButton8 = new javax.swing.JButton();
        jButton8.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        jButton8.setFocusPainted(false);
        jButton8.setForeground(new Color(255, 255, 255));
        
        //setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       setPreferredSize(new java.awt.Dimension(1000, 770));
       setSize(new java.awt.Dimension(1000, 770));
        getContentPane().setLayout(null);
        setSize(1000,770);
        getContentPane().add(c3);
        c3.setBounds(510, 650, 200, 32);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("cost");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 650, 150, 28);

        jButton1.setBackground(new Color(0, 128, 128));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("VIEW COST");
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 590, 200, 35);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("venue");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 540, 100, 28);

        c2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "TAJ HOTEL", "OBEROI HOTEL" }));
        getContentPane().add(c2);
        c2.setBounds(500, 540, 200, 32);

        c1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "MARRIAGE", "FAMILY FUNCTION", "BIRTHDAY" }));
        getContentPane().add(c1);
        c1.setBounds(500, 490, 200, 32);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("venue type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 490, 140, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" VIEW VENUE ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 400, 280, 42);

        jButton3.setBackground(new Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Feedback");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(245, 330, 247, 35);

        jButton4.setBackground(new Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(742, 330, 250, 35);

        jButton6.setBackground(new Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("View Venue");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(491, 330, 250, 35);

        jButton8.setBackground(new Color(0, 0, 153));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("Book An  Event");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1, 330, 247, 35);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\icon.png"));
        lblNewLabel.setBorder(new LineBorder(new Color(0, 0, 0), 5, true));
        lblNewLabel.setBounds(1, 1, 992, 320);
        Timer timer= new Timer(1000, new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				int n= (int) Math.floor( Math.random() * 6);
				String image=images[n];
				lblNewLabel.setIcon(new ImageIcon("src\\images\\"+ image));
			}
			
		});
		timer.start();
        getContentPane().add(lblNewLabel);
        
        label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Prateek\\Desktop\\project\\Webp.net-resizeimage (3).jpg"));
        label.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));
        label.setBounds(24, 391, 945, 320);
        getContentPane().add(label);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Feedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Home.main(null);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    	book_venue.main(null);
    	dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JTextField c3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private JLabel lblNewLabel;
    private JLabel label;
    // End of variables declaration//GEN-END:variables
}
